// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Info info
//
// swagger:model info
type Info struct {

	// Deployed git branch
	Branch string `json:"branch,omitempty"`

	// SHA from git
	Commit string `json:"commit,omitempty"`

	// Release date
	Date string `json:"date,omitempty"`

	// Application name
	Name string `json:"name,omitempty"`

	// Release version
	Release string `json:"release,omitempty"`

	// Git repository URL
	RepositoryURL string `json:"repositoryUrl,omitempty"`
}

// Validate validates this info
func (m *Info) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Info) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Info) UnmarshalBinary(b []byte) error {
	var res Info
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
