// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Builder microservice API
//
//  OpenAPI specification for LogicFM Builder microservice
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <ahamtat108@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
