// Code generated by go-swagger; DO NOT EDIT.

package rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"../pkg/models"
)

// AddNewCreatedCode is the HTTP code returned for type AddNewCreated
const AddNewCreatedCode int = 201

/*AddNewCreated Created

swagger:response addNewCreated
*/
type AddNewCreated struct {
}

// NewAddNewCreated creates AddNewCreated with default headers values
func NewAddNewCreated() *AddNewCreated {

	return &AddNewCreated{}
}

// WriteResponse to the client
func (o *AddNewCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*AddNewDefault error

swagger:response addNewDefault
*/
type AddNewDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddNewDefault creates AddNewDefault with default headers values
func NewAddNewDefault(code int) *AddNewDefault {
	if code <= 0 {
		code = 500
	}

	return &AddNewDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add new default response
func (o *AddNewDefault) WithStatusCode(code int) *AddNewDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add new default response
func (o *AddNewDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add new default response
func (o *AddNewDefault) WithPayload(payload *models.Error) *AddNewDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add new default response
func (o *AddNewDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddNewDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
