// Code generated by go-swagger; DO NOT EDIT.

package rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ahamtat/logicfm/internal/models"
)

// UpdateRuleOKCode is the HTTP code returned for type UpdateRuleOK
const UpdateRuleOKCode int = 200

/*UpdateRuleOK OK

swagger:response updateRuleOK
*/
type UpdateRuleOK struct {
}

// NewUpdateRuleOK creates UpdateRuleOK with default headers values
func NewUpdateRuleOK() *UpdateRuleOK {

	return &UpdateRuleOK{}
}

// WriteResponse to the client
func (o *UpdateRuleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*UpdateRuleDefault error

swagger:response updateRuleDefault
*/
type UpdateRuleDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateRuleDefault creates UpdateRuleDefault with default headers values
func NewUpdateRuleDefault(code int) *UpdateRuleDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateRuleDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update rule default response
func (o *UpdateRuleDefault) WithStatusCode(code int) *UpdateRuleDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update rule default response
func (o *UpdateRuleDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update rule default response
func (o *UpdateRuleDefault) WithPayload(payload *models.Error) *UpdateRuleDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update rule default response
func (o *UpdateRuleDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRuleDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
