// Code generated by go-swagger; DO NOT EDIT.

package rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"../internal/models"
)

// AddNewRuleReader is a Reader for the AddNewRule structure.
type AddNewRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddNewRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAddNewRuleCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAddNewRuleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAddNewRuleCreated creates a AddNewRuleCreated with default headers values
func NewAddNewRuleCreated() *AddNewRuleCreated {
	return &AddNewRuleCreated{}
}

/*AddNewRuleCreated handles this case with default header values.

Created
*/
type AddNewRuleCreated struct {
}

func (o *AddNewRuleCreated) Error() string {
	return fmt.Sprintf("[POST /rule/add/{musrvId}][%d] addNewRuleCreated ", 201)
}

func (o *AddNewRuleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddNewRuleDefault creates a AddNewRuleDefault with default headers values
func NewAddNewRuleDefault(code int) *AddNewRuleDefault {
	return &AddNewRuleDefault{
		_statusCode: code,
	}
}

/*AddNewRuleDefault handles this case with default header values.

error
*/
type AddNewRuleDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the add new rule default response
func (o *AddNewRuleDefault) Code() int {
	return o._statusCode
}

func (o *AddNewRuleDefault) Error() string {
	return fmt.Sprintf("[POST /rule/add/{musrvId}][%d] addNewRule default  %+v", o._statusCode, o.Payload)
}

func (o *AddNewRuleDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *AddNewRuleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
