// Code generated by go-swagger; DO NOT EDIT.

package rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ahamtat/logicfm/pkg/models"
)

// NewAddNewParams creates a new AddNewParams object
// with the default values initialized.
func NewAddNewParams() *AddNewParams {
	var ()
	return &AddNewParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddNewParamsWithTimeout creates a new AddNewParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddNewParamsWithTimeout(timeout time.Duration) *AddNewParams {
	var ()
	return &AddNewParams{

		timeout: timeout,
	}
}

// NewAddNewParamsWithContext creates a new AddNewParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddNewParamsWithContext(ctx context.Context) *AddNewParams {
	var ()
	return &AddNewParams{

		Context: ctx,
	}
}

// NewAddNewParamsWithHTTPClient creates a new AddNewParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddNewParamsWithHTTPClient(client *http.Client) *AddNewParams {
	var ()
	return &AddNewParams{
		HTTPClient: client,
	}
}

/*AddNewParams contains all the parameters to send to the API endpoint
for the add new operation typically these are written to a http.Request
*/
type AddNewParams struct {

	/*MusrvID*/
	MusrvID int64
	/*Rule*/
	Rule *models.Rule

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add new params
func (o *AddNewParams) WithTimeout(timeout time.Duration) *AddNewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add new params
func (o *AddNewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add new params
func (o *AddNewParams) WithContext(ctx context.Context) *AddNewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add new params
func (o *AddNewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add new params
func (o *AddNewParams) WithHTTPClient(client *http.Client) *AddNewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add new params
func (o *AddNewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMusrvID adds the musrvID to the add new params
func (o *AddNewParams) WithMusrvID(musrvID int64) *AddNewParams {
	o.SetMusrvID(musrvID)
	return o
}

// SetMusrvID adds the musrvId to the add new params
func (o *AddNewParams) SetMusrvID(musrvID int64) {
	o.MusrvID = musrvID
}

// WithRule adds the rule to the add new params
func (o *AddNewParams) WithRule(rule *models.Rule) *AddNewParams {
	o.SetRule(rule)
	return o
}

// SetRule adds the rule to the add new params
func (o *AddNewParams) SetRule(rule *models.Rule) {
	o.Rule = rule
}

// WriteToRequest writes these params to a swagger request
func (o *AddNewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param musrvId
	if err := r.SetPathParam("musrvId", swag.FormatInt64(o.MusrvID)); err != nil {
		return err
	}

	if o.Rule != nil {
		if err := r.SetBodyParam(o.Rule); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
