// Code generated by go-swagger; DO NOT EDIT.

package rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"../internal/models"
)

// NewUpdateRuleParams creates a new UpdateRuleParams object
// with the default values initialized.
func NewUpdateRuleParams() *UpdateRuleParams {
	var ()
	return &UpdateRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRuleParamsWithTimeout creates a new UpdateRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateRuleParamsWithTimeout(timeout time.Duration) *UpdateRuleParams {
	var ()
	return &UpdateRuleParams{

		timeout: timeout,
	}
}

// NewUpdateRuleParamsWithContext creates a new UpdateRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateRuleParamsWithContext(ctx context.Context) *UpdateRuleParams {
	var ()
	return &UpdateRuleParams{

		Context: ctx,
	}
}

// NewUpdateRuleParamsWithHTTPClient creates a new UpdateRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateRuleParamsWithHTTPClient(client *http.Client) *UpdateRuleParams {
	var ()
	return &UpdateRuleParams{
		HTTPClient: client,
	}
}

/*UpdateRuleParams contains all the parameters to send to the API endpoint
for the update rule operation typically these are written to a http.Request
*/
type UpdateRuleParams struct {

	/*ID*/
	ID int64
	/*Rule*/
	Rule *models.Rule

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update rule params
func (o *UpdateRuleParams) WithTimeout(timeout time.Duration) *UpdateRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update rule params
func (o *UpdateRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update rule params
func (o *UpdateRuleParams) WithContext(ctx context.Context) *UpdateRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update rule params
func (o *UpdateRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update rule params
func (o *UpdateRuleParams) WithHTTPClient(client *http.Client) *UpdateRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update rule params
func (o *UpdateRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update rule params
func (o *UpdateRuleParams) WithID(id int64) *UpdateRuleParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update rule params
func (o *UpdateRuleParams) SetID(id int64) {
	o.ID = id
}

// WithRule adds the rule to the update rule params
func (o *UpdateRuleParams) WithRule(rule *models.Rule) *UpdateRuleParams {
	o.SetRule(rule)
	return o
}

// SetRule adds the rule to the update rule params
func (o *UpdateRuleParams) SetRule(rule *models.Rule) {
	o.Rule = rule
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.Rule != nil {
		if err := r.SetBodyParam(o.Rule); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
